### ISSUE TITLE
Build issues with "mvn package"

### ISSUE THREAD

**Issue by ayankuma** [itsallcode/openfasttrace-demo#3]
I see the following error logs. Can someone point me in the correct direction.

`Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom (6.6 kB at 83 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.594 s
[INFO] Finished at: 2024-01-18T11:44:15Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openfasttrace: Could not resolve dependencies for project org.itsallcode:openfasttrace:jar:0.5.4: Failed to collect dependencies at com.github.kaklakariada:hamcrest-auto-matcher:jar:0.4.1: Failed to read artifact descriptor for com.github.kaklakariada:hamcrest-auto-matcher:jar:0.4.1: Could not transfer artifact com.github.kaklakariada:hamcrest-auto-matcher:pom:0.4.1 from/to jcenter (http://jcenter.bintray.com/): Transfer failed for http://jcenter.bintray.com/com/github/kaklakariada/hamcrest-auto-matcher/0.4.1/hamcrest-auto-matcher-0.4.1.pom: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

**Comment by redcatbear** [comment]
Hi @ayankuma,  I just saw your issue. That's a good motivation for me to do #2, which should also solve your problem. The instructions for the demo were quite outdated since I last touched them 2018. About time I refreh them. Stay tuned.

**Comment by redcatbear** [comment]
@ayankuma, I updated the demo and tested it with Java 17 + OFT 3.7.1. Could you please give it another try?

Your problem should be fixed with #2. Also I am happy about any feedback for the demo.

**Comment by ayankuma** [comment]
Hi Sebastian,

Many thanks, I will give it a try.
By any chance, are you in FOSDEM ? If so, how do I find you 😊.

I would love to catch up with you in person to discuss few things.
We are currently assessing if we can use OFT as a tool for Xen functional safety.
Your pointers will be appreciated.

Kind regards,
Ayan

From: Sebastian Bär ***@***.***>
Date: Thursday, 1 February 2024 at 09:33
To: itsallcode/openfasttrace-demo ***@***.***>
Cc: Ayan Kumar Halder ***@***.***>, Mention ***@***.***>
Subject: Re: [itsallcode/openfasttrace-demo] Build issues with "mvn package" (Issue #3)
CAUTION: This message has originated from an External Source. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.


@ayankuma<https://github.com/ayankuma>, I updated the demo and tested it with Java 17 + OFT 3.7.1. Could you please give it another try?

Your problem should be fixed with #2<https://github.com/itsallcode/openfasttrace-demo/issues/2>. Also I am happy about any feedback for the demo.

**Comment by redcatbear** [comment]
Hi Ayan,

I am unfortunately not at the FOSDEM. But we can definitely arrange a chat. I asked @kaklakariada, the other co-founder of OFT, he will probably join too. I am the German timezone (CET / UTC+1). Let's first find a time that works for you too and then a we can arrange a Jitsi call.

**Comment by ayankuma** [comment]
@redcatbear @kaklakariada I have sent you an email. It will be great to have an initial chat. Let me know your suitable time. I am based in UK (UTC) and my team mate is based in CET.

**Comment by redcatbear** [comment]
I forgot to close this issue after the update. Doing this now.
